# Generated by Django 6.0.3 on 2026-03-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_employee_remove_user_is_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Employer', 'Employer'), ('Employee', 'Employee')], default='Employee', max_length=20),
        ),
    ]
