# Generated by Django 6.0.3 on 2026-03-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Employer', 'Employer'), ('Employee', 'Employee')], max_length=20),
        ),
    ]
