# Generated by Django 6.0.3 on 2026-03-27 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=20)),
                ('salary_range', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('work', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('stack', models.CharField(blank=True, max_length=100)),
                ('date_published', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
