# Generated by Django 6.0.3 on 2026-03-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobListings', '0002_company_alter_joblisting_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
